BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[COMANDA] DROP CONSTRAINT [COMANDA_IdRestaurant_fkey];

-- AlterTable
ALTER TABLE [dbo].[NOTIFICARE] ADD [Destinatar] NVARCHAR(50);

-- AddForeignKey
ALTER TABLE [dbo].[COMANDA] ADD CONSTRAINT [COMANDA_IdRestaurant_fkey] FOREIGN KEY ([IdRestaurant]) REFERENCES [dbo].[RESTAURANT]([IdRestaurant]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
