BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[PRODUS] DROP CONSTRAINT [PRODUS_IdRestaurant_fkey];

-- AlterTable
ALTER TABLE [dbo].[RESTAURANT] ADD [Latitude] FLOAT(53),
[Longitude] FLOAT(53);

-- AddForeignKey
ALTER TABLE [dbo].[PRODUS] ADD CONSTRAINT [PRODUS_IdRestaurant_fkey] FOREIGN KEY ([IdRestaurant]) REFERENCES [dbo].[RESTAURANT]([IdRestaurant]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
